spring:
  datasource:
    url: jdbc:mysql://localhost:3307/sgf_prod
    username: sfg_prod_user
    password: sfg_prod_user
  jpa:
    hibernate:
      def-auto: validate
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    database: mysql
    show-sql: false
